SAC-3349 support TYPO3 v11
saccas/ext-variables pull request #2
Opened 2022-05-19 05:55 UTC by DanielSiepmann

2022-05-19 05:56 UTC, DanielSiepmann commented
I marked the extension to be compatible with our use case.
I executed rector to auto migrate most parts.
I manually checked the small code part.

I did not test the update yet. There are 0 tests within the extension. But I'll do that before marking the PR ready for review.

2022-05-19 13:42 UTC, DanielSiepmann commented
Done from my sight.

Hannes mentioned there is an v11 version on https://github.com/visol/ext-variables.
I try to rebase and contribute our changes back.

They didn't drop older TYPO3 and PHP, need to extend the CI to also test those versions.

2022-05-19 14:27 UTC, DanielSiepmann commented
I've created a new branch based on this one, rebased on v11 from the original repo.
The PR is available at: https://github.com/visol/ext-variables/pull/21

I hope they merge it and release a version.
I would keep our fork and use the branch from https://github.com/visol/ext-variables/pull/21 otherwise.

2022-05-31 06:58 UTC, s12r requested changes
found only a version mismatch between `composer.json` and `ext_emconf.php`, the rest seems ok  so far

2022-05-31 06:58 UTC, s12r commented on ext_emconf.php
> +            'php' => '7.0.0-7.4.99',
Doesn't match with `composer.json`'s
```
  ...
  "typo3/cms-core": "^11.5",
  "php": "8.1.*"
  ...
```
... or have I missed something?

2022-05-31 09:03 UTC, s12r approved these changes

2022-05-31 09:04 UTC, merged